# Generated by Django 5.0.4 on 2024-05-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=5, verbose_name='symbol'),
        ),
        migrations.AlterField(
            model_name='spends',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
